In [2]:
import pandas as pd
import numpy as np
from  sklearn.model_selection import train_test_split

In [3]:
df_train = pd.read_csv('train.csv')


In [4]:
df_train.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [5]:
df_test = pd.read_csv('test.csv')
df_test.head()

ID  X0 X1  X2 X3 X4 X5 X6 X8  X10  ...  X375  X376  X377  X378  X379  X380  \
0   1  az  v   n  f  d  t  a  w    0  ...     0     0     0     1     0     0   
1   2   t  b  ai  a  d  b  g  y    0  ...     0     0     1     0     0     0   
2   3  az  v  as  f  d  a  j  j    0  ...     0     0     0     1     0     0   
3   4  az  l   n  f  d  z  l  n    0  ...     0     0     0     1     0     0   
4   5   w  s  as  c  d  y  i  m    0  ...     1     0     0     0     0     0   

   X382  X383  X384  X385  
0     0     0     0     0  
1     0     0     0     0  
2     0     0     0     0  
3     0     0     0     0  
4     0     0     0     0  

[5 rows x 377 columns]

In [6]:
df_train.shape

(4209, 378)

In [7]:
df_test.shape

(4209, 377)

In [8]:
df_train.columns

Index(['ID', 'y', 'X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8',
       ...
       'X375', 'X376', 'X377', 'X378', 'X379', 'X380', 'X382', 'X383', 'X384',
       'X385'],
      dtype='object', length=378)

In [9]:
df_test.columns

Index(['ID', 'X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8', 'X10',
       ...
       'X375', 'X376', 'X377', 'X378', 'X379', 'X380', 'X382', 'X383', 'X384',
       'X385'],
      dtype='object', length=377)

In [10]:
df_train.describe()

ID            y          X10     X11          X12  \
count  4209.000000  4209.000000  4209.000000  4209.0  4209.000000   
mean   4205.960798   100.669318     0.013305     0.0     0.075077   
std    2437.608688    12.679381     0.114590     0.0     0.263547   
min       0.000000    72.110000     0.000000     0.0     0.000000   
25%    2095.000000    90.820000     0.000000     0.0     0.000000   
50%    4220.000000    99.150000     0.000000     0.0     0.000000   
75%    6314.000000   109.010000     0.000000     0.0     0.000000   
max    8417.000000   265.320000     1.000000     0.0     1.000000   

               X13          X14          X15          X16          X17  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.057971     0.428130     0.000475     0.002613     0.007603  ...   
std       0.233716     0.494867     0.021796     0.051061     0.086872  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     1.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.318841     0.057258     0.314802     0.020670     0.009503   
std       0.466082     0.232363     0.464492     0.142294     0.097033   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.007603     0.001663     0.000475     0.001426  
std       0.089524     0.086872     0.040752     0.021796     0.037734  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 370 columns]

In [11]:
#If for any column(s), the variance is equal to zero, then you need to remove those variable(s).
df_train.var

<bound method DataFrame.var of         ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k  v  at  a  d   u  j  o  ...     0     0     1     0   
1        6   88.53   k  t  av  e  d   y  l  o  ...     1     0     0     0   
2        7   76.26  az  w   n  c  d   x  j  x  ...     0     0     0     0   
3        9   80.62  az  t   n  f  d   x  l  e  ...     0     0     0     0   
4       13   78.02  az  v   n  f  d   h  d  n  ...     0     0     0     0   
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4207  8415   87.48  al  r   e  f  d  aa  l  u  ...     0     0     0     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X3

In [12]:
(df_train.var()==0).values

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [13]:
(df_train.var()==0).sort_values(ascending=False)

X289     True
X107     True
X268     True
X347     True
X233     True
        ...  
X257    False
X258    False
X259    False
X260    False
ID      False
Length: 370, dtype: bool

In [14]:
var_zero = df_train.var()[df_train.var()==0].index.values

In [15]:
var_zero

array(['X11', 'X93', 'X107', 'X233', 'X235', 'X268', 'X289', 'X290',
       'X293', 'X297', 'X330', 'X347'], dtype=object)

In [16]:
df_train = df_train.drop(var_zero,axis=1)

In [17]:
var_zero

array(['X11', 'X93', 'X107', 'X233', 'X235', 'X268', 'X289', 'X290',
       'X293', 'X297', 'X330', 'X347'], dtype=object)

In [18]:
(df_train.var()==0).values

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [19]:
# Check for null and unique values for test and train sets.
df_train.isnull().sum().values

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [20]:
df_test.isnull().sum().values

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [21]:
df_train.isnull().any

<bound method DataFrame.any of          ID      y     X0     X1     X2     X3     X4     X5     X6     X8  \
0     False  False  False  False  False  False  False  False  False  False   
1     False  False  False  False  False  False  False  False  False  False   
2     False  False  False  False  False  False  False  False  False  False   
3     False  False  False  False  False  False  False  False  False  False   
4     False  False  False  False  False  False  False  False  False  False   
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
4204  False  False  False  False  False  False  False  False  False  False   
4205  False  False  False  False  False  False  False  False  False  False   
4206  False  False  False  False  False  False  False  False  False  False   
4207  False  False  False  False  False  False  False  False  False  False   
4208  False  False  False  False  False  False  False  False  False  False   

      ...   X375   X376   X377  

In [22]:
# Check for uniqe values
df_train.nunique()

ID      4209
y       2545
X0        47
X1        27
X2        44
        ... 
X380       2
X382       2
X383       2
X384       2
X385       2
Length: 366, dtype: int64

In [23]:
df_test.nunique()

ID      4209
X0        49
X1        27
X2        45
X3         7
        ... 
X380       2
X382       2
X383       2
X384       2
X385       2
Length: 377, dtype: int64

In [24]:
df_train.head(20)

ID       y  X0  X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0    0  130.81   k   v  at  a  d  u  j  o  ...     0     0     1     0     0   
1    6   88.53   k   t  av  e  d  y  l  o  ...     1     0     0     0     0   
2    7   76.26  az   w   n  c  d  x  j  x  ...     0     0     0     0     0   
3    9   80.62  az   t   n  f  d  x  l  e  ...     0     0     0     0     0   
4   13   78.02  az   v   n  f  d  h  d  n  ...     0     0     0     0     0   
5   18   92.93   t   b   e  c  d  g  h  s  ...     0     0     1     0     0   
6   24  128.76  al   r   e  f  d  f  h  s  ...     0     0     0     0     0   
7   25   91.91   o   l  as  f  d  f  j  a  ...     0     0     0     0     0   
8   27  108.67   w   s  as  e  d  f  i  h  ...     1     0     0     0     0   
9   30  126.99   j   b  aq  c  d  f  a  e  ...     0     0     1     0     0   
10  31  102.09   h   r   r  f  d  f  h  p  ...     0     0     0     0     0   
11  32   98.12  al   r   e  f  d  f  h  o  ...     0     0     0     0     0   
12  34   82.62   s   b  ai  c  d  f  g  m  ...     0     0     1     0     0   
13  36   94.12  al   r   e  f  d  j  h  o  ...     0     0     0     0     0   
14  37   99.15   o   s  as  e  d  j  g  m  ...     1     0     0     0     0   
15  38   93.64   n   l  ak  f  d  j  d  k  ...     0     0     0     0     0   
16  39  106.10  al   r   e  f  d  j  h  o  ...     0     0     0     0     0   
17  40  114.13  ay  aa  as  c  d  j  c  d  ...     0     0     1     0     0   
18  44   89.81   f   c   m  c  d  j  d  e  ...     0     0     1     0     0   
19  47   90.81   n   a  ak  f  d  j  i  s  ...     0     0     0     0     0   

    X380  X382  X383  X384  X385  
0      0     0     0     0     0  
1      0     0     0     0     0  
2      0     1     0     0     0  
3      0     0     0     0     0  
4      0     0     0     0     0  
5      0     0     0     0     0  
6      0     0     0     0     0  
7      0     0     0     0     0  
8      0     0     0     0     0  
9      0     0     0     0     0  
10     0     0     0     0     0  
11     0     0     0     0     0  
12     0     0     0     0     0  
13     0     0     0     0     0  
14     0     0     0     0     0  
15     0     0     0     0     0  
16     0     0     0     0     0  
17     0     0     0     0     0  
18     0     0     0     0     0  
19     0     0     0     0     0  

[20 rows x 366 columns]

In [25]:
object_dtype = df_train.select_dtypes(include= [object])
object_dtype

X0 X1  X2 X3 X4  X5 X6 X8
0      k  v  at  a  d   u  j  o
1      k  t  av  e  d   y  l  o
2     az  w   n  c  d   x  j  x
3     az  t   n  f  d   x  l  e
4     az  v   n  f  d   h  d  n
...   .. ..  .. .. ..  .. .. ..
4204  ak  s  as  c  d  aa  d  q
4205   j  o   t  d  d  aa  h  h
4206  ak  v   r  a  d  aa  g  e
4207  al  r   e  f  d  aa  l  u
4208   z  r  ae  c  d  aa  g  w

[4209 rows x 8 columns]

In [26]:
object_dtype_col = object_dtype.columns
object_dtype_col

Index(['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8'], dtype='object')

In [27]:
# Apply label encoder.
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

In [28]:
df_train['X0'].unique()

array(['k', 'az', 't', 'al', 'o', 'w', 'j', 'h', 's', 'n', 'ay', 'f', 'x',
       'y', 'aj', 'ak', 'am', 'z', 'q', 'at', 'ap', 'v', 'af', 'a', 'e',
       'ai', 'd', 'aq', 'c', 'aa', 'ba', 'as', 'i', 'r', 'b', 'ax', 'bc',
       'u', 'ad', 'au', 'm', 'l', 'aw', 'ao', 'ac', 'g', 'ab'],
      dtype=object)

In [29]:
## Tranform object data to number ineger
df_train['X0'] = label_encoder.fit_transform(df_train['X0'])

In [30]:
df_train['X0'].unique()

array([32, 20, 40,  9, 36, 43, 31, 29, 39, 35, 19, 27, 44, 45,  7,  8, 10,
       46, 37, 15, 12, 42,  5,  0, 26,  6, 25, 13, 24,  1, 22, 14, 30, 38,
       21, 18, 23, 41,  4, 16, 34, 33, 17, 11,  3, 28,  2])

In [31]:
## Aply lebel encoder for all columns that have object dtype
df_train['X0'] = label_encoder.fit_transform(df_train['X0'])
df_train['X1'] = label_encoder.fit_transform(df_train['X1'])
df_train['X2'] = label_encoder.fit_transform(df_train['X2'])
df_train['X3'] = label_encoder.fit_transform(df_train['X3'])
df_train['X4'] = label_encoder.fit_transform(df_train['X4'])
df_train['X5'] = label_encoder.fit_transform(df_train['X5'])
df_train['X6'] = label_encoder.fit_transform(df_train['X6'])
df_train['X8'] = label_encoder.fit_transform(df_train['X8'])

In [32]:
df_train.head()

ID       y  X0  X1  X2  X3  X4  X5  X6  X8  ...  X375  X376  X377  X378  \
0   0  130.81  32  23  17   0   3  24   9  14  ...     0     0     1     0   
1   6   88.53  32  21  19   4   3  28  11  14  ...     1     0     0     0   
2   7   76.26  20  24  34   2   3  27   9  23  ...     0     0     0     0   
3   9   80.62  20  21  34   5   3  27  11   4  ...     0     0     0     0   
4  13   78.02  20  23  34   5   3  12   3  13  ...     0     0     0     0   

   X379  X380  X382  X383  X384  X385  
0     0     0     0     0     0     0  
1     0     0     0     0     0     0  
2     0     0     1     0     0     0  
3     0     0     0     0     0     0  
4     0     0     0     0     0     0  

[5 rows x 366 columns]

In [33]:
# Perform PCA
from sklearn.decomposition import PCA
pca = PCA(n_components= 12,svd_solver='full')

In [34]:
x = df_train.drop('y', axis= 1)
y = df_train.y

In [133]:
# split data
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y ,test_size=0.2,random_state=42)


In [40]:
pca.fit(x)

PCA(n_components=12, svd_solver='full')

In [41]:
pca.n_components_


12

In [42]:
pca.explained_variance_ratio_


array([9.99915408e-01, 3.43250074e-05, 1.91351988e-05, 1.09402163e-05,
       8.24910539e-06, 6.58920898e-06, 1.42452645e-06, 6.65804820e-07,
       3.88293669e-07, 2.63001372e-07, 2.16183012e-07, 2.11583571e-07])

In [43]:
pca_X_train = pd.DataFrame(pca.transform(x_train))
pca_X_val = pd.DataFrame(pca.transform(x_test)) 
# pca_test = pd.DataFrame(pca.transform(df_test))

In [124]:
pca_X_train.shape

(842, 12)

In [111]:
df_train.head()

y  X0  X1  X2  X3  X4  X5  X6  X8  X10  ...  X375  X376  X377  X378  \
0  130.81  32  23  17   0   3  24   9  14    0  ...     0     0     1     0   
1   88.53  32  21  19   4   3  28  11  14    0  ...     1     0     0     0   
2   76.26  20  24  34   2   3  27   9  23    0  ...     0     0     0     0   
3   80.62  20  21  34   5   3  27  11   4    0  ...     0     0     0     0   
4   78.02  20  23  34   5   3  12   3  13    0  ...     0     0     0     0   

   X379  X380  X382  X383  X384  X385  
0     0     0     0     0     0     0  
1     0     0     0     0     0     0  
2     0     0     1     0     0     0  
3     0     0     0     0     0     0  
4     0     0     0     0     0     0  

[5 rows x 365 columns]

In [46]:
label_encoder = preprocessing.LabelEncoder()
object_dtype = df_test.select_dtypes(include= [object])
obj_dtype_col = object_dtype.columns
obj_dtype_col

Index(['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8'], dtype='object')

In [47]:
df_test['X0'] = label_encoder.fit_transform(df_test['X0'])
df_test['X1'] = label_encoder.fit_transform(df_test['X1'])
df_test['X2'] = label_encoder.fit_transform(df_test['X2'])
df_test['X3'] = label_encoder.fit_transform(df_test['X3'])
df_test['X4'] = label_encoder.fit_transform(df_test['X4'])
df_test['X5'] = label_encoder.fit_transform(df_test['X5'])
df_test['X6'] = label_encoder.fit_transform(df_test['X6'])
df_test['X8'] = label_encoder.fit_transform(df_test['X8'])

In [48]:
df_test['X8'].unique()

array([22, 24,  9, 13, 12, 18,  0, 21, 17, 14, 19,  7,  2, 10, 15, 20,  3,
        6,  1, 16,  4, 11,  5,  8, 23])

In [51]:
## Predict using xgboots
import xgboost as xgb
model = xgb.XGBRegressor(objective='reg:linear',learning_rate=0.1)


In [52]:
model.fit(pca_X_train,y_train)

[16:38:41] WARNING: /workspace/src/objective/regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(base_score=0.5, booster=None, colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints=None,
             learning_rate=0.1, max_delta_step=0, max_depth=6,
             min_child_weight=1, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=0, num_parallel_tree=1,
             objective='reg:linear', random_state=0, reg_alpha=0, reg_lambda=1,
             scale_pos_weight=1, subsample=1, tree_method=None,
             validate_parameters=False, verbosity=None)

In [127]:
y_pred = model.predict(pca_X_val)
y_pred.shape

(842,)

In [132]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error( y_test, y_pred)
mse

85.95207456130629